# Generated by Django 2.2.28 on 2023-05-02 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230502_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 5, 2, 22, 14, 38, 190741), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 5, 2, 22, 14, 38, 191716), verbose_name='Дата комментария'),
        ),
    ]
